name: Build and run on all OSes
on: [push]
jobs:
  release:
    runs-on: windows-latest
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      # - name: Setup Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: "1.17.3"
      - name: Build
        run: go build -v ./...
      - name: Run the binary
        run: .\three_oses.exe
      # - name: Go run
      #   run: go run .
