name: Build and run on all OSes
on: [push]
jobs:
  release:
    runs-on: windows-latest
    # runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.3"
      - name: Go run
      - name: Build
        run: go build -v ./...
      - name: Run the binary
        run: sudo ./my_traceroute -remote "heisse.de"
      # - name: Go run
      #   run: go run .
